universal8895: fix compilations errors due to init scripts
Fixes compilation errors looking something like:

host_init_verifier: Command 'mkdir /efs/pfw_data 0760 spay spay' (device/samsung/universal8895-common/ramdisk/etc/init.samsungexynos8895.rc:140) failed: Unable to decode UID for 'spay': getpwnam failed: No such file or directory

host_init_verifier: Command 'mkdir /data/misc/integrity 0775 vendor_audit system' (device/samsung/universal8895-common/ramdisk/etc/init.samsung.rc:212) failed: Unable to decode UID for 'vendor_audit': getpwnam failed: No such file or directory

host_init_verifier: Command 'restorecon --recursive --force /efs' (device/samsung/universal8895-common/ramdisk/etc/init.samsung.rc:288) failed: bad flag --force